src/Entity/Capteur.php
<?php

namespace App\Entity;

use App\Repository\CapteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CapteurRepository::class)]
class Capteur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 254)]
    private ?string $dev_eui = null;

    #[ORM\Column(length: 254)]
    private ?string $marque = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $reseau = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\OneToMany(mappedBy: 'capteur', targetEntity: Releve::class)]
    private Collection $releves;

    public function __construct()
    {
        $this->releves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDevEui(): ?string
    {
        return $this->dev_eui;
    }

    public function setDevEui(string $dev_eui): self
    {
        $this->dev_eui = $dev_eui;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getReseau(): ?string
    {
        return $this->reseau;
    }

    public function setReseau(?string $reseau): self
    {
        $this->reseau = $reseau;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Releve>
     */
    public function getReleves(): Collection
    {
        return $this->releves;
    }

    public function addRelefe(Releve $relefe): self
    {
        if (!$this->releves->contains($relefe)) {
            $this->releves->add($relefe);
            $relefe->setCapteur($this);
        }

        return $this;
    }

    public function removeRelefe(Releve $relefe): self
    {
        if ($this->releves->removeElement($relefe)) {
            // set the owning side to null (unless already changed)
            if ($relefe->getCapteur() === $this) {
                $relefe->setCapteur(null);
            }
        }

        return $this;
    }
}

src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $intitule_cours = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Salle $salle = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?Enseignant $enseignant = null;

    #[ORM\ManyToOne(inversedBy: 'cours')]
    private ?GroupeEtudiant $groupe_etu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntituleCours(): ?string
    {
        return $this->intitule_cours;
    }

    public function setIntituleCours(?string $intitule_cours): self
    {
        $this->intitule_cours = $intitule_cours;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getSalle(): ?Salle
    {
        return $this->salle;
    }

    public function setSalle(?Salle $salle): self
    {
        $this->salle = $salle;

        return $this;
    }

    public function getEnseignant(): ?Enseignant
    {
        return $this->enseignant;
    }

    public function setEnseignant(?Enseignant $enseignant): self
    {
        $this->enseignant = $enseignant;

        return $this;
    }

    public function getGroupeEtu(): ?GroupeEtudiant
    {
        return $this->groupe_etu;
    }

    public function setGroupeEtu(?GroupeEtudiant $groupe_etu): self
    {
        $this->groupe_etu = $groupe_etu;

        return $this;
    }
}

src/Entity/Salle.php
<?php

namespace App\Entity;

use App\Repository\SalleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SalleRepository::class)]
class Salle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 254)]
    private ?string $nom_salle = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacite = null;

    #[ORM\ManyToOne(inversedBy: 'salles')]
    private ?Batiment $batiment = null;

    #[ORM\OneToMany(mappedBy: 'salle', targetEntity: Cours::class)]
    private Collection $cours;

    #[ORM\OneToMany(mappedBy: 'salle', targetEntity: Releve::class)]
    private Collection $releves;

    public function __construct()
    {
        $this->cours = new ArrayCollection();
        $this->releves = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomSalle(): ?string
    {
        return $this->nom_salle;
    }

    public function setNomSalle(string $nom_salle): self
    {
        $this->nom_salle = $nom_salle;

        return $this;
    }

    public function getCapacite(): ?int
    {
        return $this->capacite;
    }

    public function setCapacite(?int $capacite): self
    {
        $this->capacite = $capacite;

        return $this;
    }

    public function getBatiment(): ?Batiment
    {
        return $this->batiment;
    }

    public function setBatiment(?Batiment $batiment): self
    {
        $this->batiment = $batiment;

        return $this;
    }

    /**
     * @return Collection<int, Cours>
     */
    public function getCours(): Collection
    {
        return $this->cours;
    }

    public function addCours(Cours $cours): self
    {
        if (!$this->cours->contains($cours)) {
            $this->cours->add($cours);
            $cours->setSalle($this);
        }

        return $this;
    }

    public function removeCours(Cours $cours): self
    {
        if ($this->cours->removeElement($cours)) {
            if ($cours->getSalle() === $this) {
                $cours->setSalle(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNomSalle();
    }

    /**
     * @return Collection<int, Releve>
     */
    public function getReleves(): Collection
    {
        return $this->releves;
    }

    public function addReleve(Releve $releve): self
    {
        if (!$this->releves->contains($releve)) {
            $this->releves->add($releve);
            $releve->setSalle($this);
        }

        return $this;
    }

    public function removeReleve(Releve $releve): self
    {
        if ($this->releves->removeElement($releve)) {
            if ($releve->getSalle() === $this) {
                $releve->setSalle(null);
            }
        }
        return $this;
    }
}

templates/dashboard/database_state.html.twig
{% extends 'template.html.twig' %}

{% block javascripts %}
    {{ encore_entry_script_tags('fetcher') }}
{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            {% if (latest != null) and (earliest != null) %}
                <p class="col-6">Donnée la plus ancienne: {{ earliest|date('m-d-Y H:i:s') }}</p>
                <p class="col-6">Donnée la plus récente: {{ latest|date('m-d-Y H:i:s') }}</p>
            {% else %}
                <p class="col-12">Aucune donnée trouvée</p>
            {% endif %}

            <div class="mb-3 col-12">
                <div class="row">
                    <div class="col-6">
                        <label for="date_debut" class="form-label required">Date debut (inclus)</label>
                        {% if (earliest != null) %}
                            <input type="date" id="date_debut" name="date_debut" required="required" class="form-control" value="{{ earliest|date('Y-m-d') }}">
                        {% else %}
                            <input type="date" id="date_debut" name="date_debut" required="required" class="form-control">
                        {% endif %}
                    </div>
                    <div class="col-6">
                        <label for="date_fin" class="form-label required">Date fin (exclus)</label>
                        {% if (latest != null) %}
                            <input type="date" id="date_fin" name="date_fin" required="required" class="form-control" value="{{ latest|date('Y-m-d') }}">
                        {% else %}
                            <input type="date" id="date_fin" name="date_fin" required="required" class="form-control">
                        {% endif %}
                    </div>
                    <div>
                        <button id="dates_Confirmer" class="btn-primary btn mt-1" type="button" name="Confirmer" onclick="actu();">Récupérer</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/dashboard/details_capteur.html.twig
{% extends 'template.html.twig' %}

{% block javascripts %}
    {{ encore_entry_script_tags('detail_capteur') }}
{% endblock %}

{% block stylesheets %}
    <style>
        .loader {
            border: 2px solid #f3f3f3; /* Light grey */
            border-top: 2px solid #3498db; /* Blue */
            border-radius: 50%;
            width: 20px;
            height: 20px;
            animation: spin 2s linear infinite;
        }

        @keyframes spin {
            0% {
                transform: rotate(0deg);
            }
            100% {
                transform: rotate(360deg);
            }
        }
    </style>
{% endblock %}

{% block body %}
    <h1>Capteur: {{ capteur.devEui }}</h1>

    <div class="container-fluid">
        <h2>Détails</h2>
        <ul>
            <li><strong>Marque</strong>: {{ capteur.marque }}</li>
            <li><strong>Réseau</strong>: {{ capteur.reseau }}</li>
            <li><strong>Dernière salle</strong>:
                {% if salle %}
                    <a href="{{ path('salle.details', {id: salle.id}) }}">{{ salle }}</a>
                {% else %}
                    Aucune salle trouvée
                {% endif %}
            </li>
            <li><strong>Description</strong>: {{ capteur.description }}</li>
            <li><strong>Date de début</strong>: {{ capteur.dateDebut|date('d/m/Y') }}</li>
            <li><strong>Date de fin</strong>: {{ capteur.dateFin|date('d/m/Y') }}</li>
        </ul>

        <div class="mb-3 container-fluid">
            <div class="row">
                <div class="col-6">
                    <label for="date_debut" class="form-label required">Date debut</label>
                    <input type="date" id="date_debut" name="date_debut" required="required" class="form-control" value="{{ from|date('Y-m-d') }}">
                </div>
                <div class="col-6">
                    <label for="date_fin" class="form-label required">Date fin</label>
                    <input type="date" id="date_fin" name="date_fin" required="required" class="form-control" value="{{ to|date('Y-m-d') }}">
                </div>
            </div>
        </div>

        <div class="mb-3 container-fluid">
            <div class="row">
                <button id="dates_Confirmer" class="btn-primary btn col-2" type="button" name="Confirmer" onclick="makeRequest();">Confirmer</button>
            </div>
            <div style="display:none" id="loader" class="loader col-3 mt-1"></div>
{#            <p id="loading" style="display:none"><img width="5%" height="auto" src="" id="loading_img"/> Please Wait</p>#}
        </div>


    </div>

    <div id="graphs" class="container-fluid border-bottom">
        <div class="row">
            <h2>Relevés</h2>
            <div class="chart-container col-12 border-bottom" style="position: relative;">
                <canvas data-co2-data="{{ co2 }}" class="my-4 w-100" id="co2Chart" width="900" height="380"></canvas>
            </div>
            <div class="chart-container col-12 border-bottom border-start" style="position: relative;">
                <canvas data-hum-data="{{ humidite }}" class="my-4 w-100" id="humChart" width="900" height="380"></canvas>
            </div>
            <div class="chart-container col-12 border-right" style="position: relative;">
                <canvas data-temp-data="{{ temperature }}" class="my-4 w-100" id="tempChart" width="900" height="380"></canvas>
            </div>
        </div>
    </div>

    <div class="mb-3 mt-3">
{#        <button class="btn btn-danger">Supprimer</button>#}
        <a href="{{ path('capteurs.delete', {id: capteur.id}) }}" class="btn btn-danger">Supprimer</a>
    </div>
{% endblock %}

templates/dashboard/details_salle.html.twig
{% extends 'template.html.twig' %}

{% block body %}
    <h1>{{ salle.nomSalle }}</h1>

    <div class="row">
        <h2>Dernières mesures:</h2>
        {% if co2 %}
        <p>CO2: {{ co2.valeur }}</p>
        {% endif %}
        {% if temperature %}
        <p>Temperature: {{ temperature.valeur }}</p>
        {% endif %}
        {% if humidite %}
        <p>Humidite:    {{ humidite.valeur }}</p>
        {% endif %}

        <h2>Capteurs:</h2>
        <ul>
            {% for c in capteurs %}
                <li>
                    <a href="{{ path('capteurs.details', {id: c.id}) }}">{{ c.devEui }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/dashboard/home.html.twig
{% extends 'template.html.twig' %}

{% block javascripts %}
    {{ encore_entry_script_tags('home') }}
{% endblock %}

{% block body %}
    <h1>Home</h1>
    <div class="container-fluid">
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="col-4">
                <strong class="me-3">Co2</strong>
                <div class="input-group me-2">
                    <label for="inputCo2"></label><input type="number" id="inputCo2" name="inputCo2" value="{{ co2_threshold }}">
                </div>
            </div>
            <div class="col-4">
                <strong class="me-3">Humidité</strong>
                <div class="input-group me-2">
                    <label for="inputHum"></label><input type="number" id="inputHum" name="inputHum" value="{{ hum_threshold }}">
                </div>
            </div>
            <div class="col-4">
                <strong class="me-3">Température</strong>
                <div class="input-group me-2">
                    <label for="inputTemp"></label><input type="number" id="inputTemp" name="inputTemp" value="{{ temp_threshold }}">
                </div>
            </div>
        </div>

        <div class="mt-3 mb-1">
            <div class="row">
                <div class="col-6">
                    <label for="date_debut" class="form-label required">Date debut</label>
                    <input type="date" id="date_debut" name="date_debut" required="required" class="form-control" value="{{ from|date('Y-m-d') }}">
                </div>
                <div class="col-6">
                    <label for="date_fin" class="form-label required">Date fin</label>
                    <input type="date" id="date_fin" name="date_fin" required="required" class="form-control" value="{{ to|date('Y-m-d') }}">
                </div>
            </div>
        </div>

        <div class="mb-3">
            <button id="Confirmer" class="btn-primary btn mt-1" type="button" name="Confirmer" onclick="actu();">Confirmer</button>
            <div style="display:none" id="loader" class="loader col-3 mt-1"></div>
        </div>

        {% set freq = 10 %}

        <h2 class="border-top">Ventilation</h2>
        {% if co2_data is empty %}
            <p> Aucune salle n'a dépassé le seuil indiqué dans la période recherchée. </p>
        {% else %}
            <ul>
                {% for data in co2_data%}
                    <li><a href="{{ path('salle.details', {id:data[3]}) }}">{{data[1]}}</a> a <strong>{{data[2]}} relevés</strong> dépassant les <strong>{{co2_threshold}} ppm</strong> soit <strong>{{ ((data[2]*freq)/60)|round(0, 'floor') }} heures et {{ (data[2]*freq)%60 }} minutes </strong> au-dessus du seuil.</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h2 class="border-top">Humidité</h2>
        {% if hum_data is empty %}
            <p> Aucune salle n'a dépassé le seuil indiqué dans la période recherchée. </p>
        {% else %}
            <ul>
                {% for data in hum_data%}
                    <li><a href="{{ path('salle.details', {id:data[3]}) }}">{{data[1]}}</a> a <strong>{{data[2]}} relevés</strong> dépassant <strong>{{ hum_threshold }}% d'humidité</strong> soit <strong>{{ ((data[2]*freq)/60)|round(0, 'floor') }} heures et {{ (data[2]*freq)%60 }} minutes </strong> au-dessus du seuil.</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h2 class="border-top">Température</h2>
        {% if temp_data is empty %}
            <p> Aucune salle n'a dépassé le seuil indiqué dans la période recherchée. </p>
        {% else %}
            <ul>
                {% for data in temp_data%}
                    <li><a href="{{ path('salle.details', {id:data[3]}) }}">{{data[1]}}</a> a <strong>{{data[2]}} relevés</strong> dépassant <strong>{{ temp_threshold }}°C</strong> soit <strong>{{ ((data[2]*freq)/60)|round(0, 'floor') }} heures et {{ (data[2]*freq)%60 }} minutes </strong> au-dessus du seuil.</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>

{% endblock %}

templates/dashboard/index.html.twig
{% extends 'template.html.twig' %}

{% block javascripts %}
  {{ encore_entry_script_tags('dashboard') }}
{% endblock %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
          <svg class="bi"><use href="#calendar3"/></svg>
          This week
        </button>
      </div>
    </div>

    <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

    <h2>Section title</h2>
    <div class="table-responsive small">
      <table class="table table-striped table-sm">
        <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Header</th>
          <th scope="col">Header</th>
          <th scope="col">Header</th>
          <th scope="col">Header</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td>1,001</td>
          <td>random</td>
          <td>data</td>
          <td>placeholder</td>
          <td>text</td>
        </tr>
        <tr>
          <td>1,002</td>
          <td>placeholder</td>
          <td>irrelevant</td>
          <td>visual</td>
          <td>layout</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>data</td>
          <td>rich</td>
          <td>dashboard</td>
          <td>tabular</td>
        </tr>
        <tr>
          <td>1,003</td>
          <td>information</td>
          <td>placeholder</td>
          <td>illustrative</td>
          <td>data</td>
        </tr>
        <tr>
          <td>1,004</td>
          <td>text</td>
          <td>random</td>
          <td>layout</td>
          <td>dashboard</td>
        </tr>
        <tr>
          <td>1,005</td>
          <td>dashboard</td>
          <td>irrelevant</td>
          <td>text</td>
          <td>placeholder</td>
        </tr>
        <tr>
          <td>1,006</td>
          <td>dashboard</td>
          <td>illustrative</td>
          <td>rich</td>
          <td>data</td>
        </tr>
        <tr>
          <td>1,007</td>
          <td>placeholder</td>
          <td>tabular</td>
          <td>information</td>
          <td>irrelevant</td>
        </tr>
        <tr>
          <td>1,008</td>
          <td>random</td>
          <td>data</td>
          <td>placeholder</td>
          <td>text</td>
        </tr>
        <tr>
          <td>1,009</td>
          <td>placeholder</td>
          <td>irrelevant</td>
          <td>visual</td>
          <td>layout</td>
        </tr>
        <tr>
          <td>1,010</td>
          <td>data</td>
          <td>rich</td>
          <td>dashboard</td>
          <td>tabular</td>
        </tr>
        <tr>
          <td>1,011</td>
          <td>information</td>
          <td>placeholder</td>
          <td>illustrative</td>
          <td>data</td>
        </tr>
        <tr>
          <td>1,012</td>
          <td>text</td>
          <td>placeholder</td>
          <td>layout</td>
          <td>dashboard</td>
        </tr>
        <tr>
          <td>1,013</td>
          <td>dashboard</td>
          <td>irrelevant</td>
          <td>text</td>
          <td>visual</td>
        </tr>
        <tr>
          <td>1,014</td>
          <td>dashboard</td>
          <td>illustrative</td>
          <td>rich</td>
          <td>data</td>
        </tr>
        <tr>
          <td>1,015</td>
          <td>random</td>
          <td>tabular</td>
          <td>information</td>
          <td>text</td>
        </tr>
        </tbody>
      </table>
    </div>
{% endblock %}

templates/dashboard/listeCapteurs.html.twig
{% extends 'template.html.twig' %}

{% block modals %}
{#    <!-- Modal -->#}
{#    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#        <div class="modal-dialog">#}
{#            <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                    <h5 class="modal-title" id="exampleModalLabel">Saisie d'un nouveau Capteur</h5>#}
{#                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>#}
{#                </div>#}
{#                <div class="modal-body">#}
{#                    {{ form_start(capForm) }}#}
{#                    <div class="row">#}
{#                        <div class="col">{{ form_row(capForm.dev_eui) }}</div>#}
{#                        <div class="col">{{ form_row(capForm.marque) }}</div>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        <div class="col">{{ form_row(capForm.reseau) }}</div>#}
{#                        <div class="col">{{ form_row(capForm.salle) }}</div>#}
{#                    </div>#}
{#                    <div class="row">#}
{#                        <div class="col">{{ form_row(capForm.date_debut) }}</div>#}
{#                        <div class="col">{{ form_row(capForm.date_fin) }}</div>#}
{#                    </div>#}
{#                    {{ form_row(capForm.description) }}#}
{#                </div>#}
{#                <div class="modal-footer">#}
{#                    {{ form_rest(capForm) }}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{% endblock %}

{% block body %}
{#    <label for="state"> ALED#}
{#        <select class="form-select select2" name="state">#}
{#            <option value="DEF"></option>#}
{#            <option value="AL">Alabama</option>#}
{#            <option value="WY">Wyoming</option>#}
{#        </select>#}
{#    </label>#}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Capteurs</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
                <button type="button" class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">Ajouter</button>
        </div>
    </div>
    <div class="table-responsive small">
        <table class="table table-striped table-sm" id="capteurs_table">
            <thead>
            <tr>
                <th scope="col">devEui</th>
                <th scope="col">marque</th>
                <th scope="col">réseau</th>
{#                <th scope="col">salle</th>#}
                <th scope="col">description</th>
                <th scope="col">date debut</th>
                <th scope="col">date fin</th>
            </tr>
            </thead>
            <tbody>
            {% for c in data%}
                <tr>
                    <td><a href="{{ path('capteurs.details', {id: c.id}) }}">{{ c.devEui }}</a></td>
                    <td>{{ c.marque }}</td>
                    <td>{{ c.reseau }}</td>
{#                    <td>#}
{#                    {% if c.salle %}#}
{#                        <a href="{{ path('salle.details', {id: c.salle.id}) }}">{{ c.salle.nomSalle }}</a>#}
{#                    {% endif %}#}
{#                    </td>#}
                    <td>{{ c.description }}</td>
                    <td>{{ c.dateDebut|date('d/m/Y') }}</td>
                    <td>{{ c.dateFin|date('d/m/Y') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('form') }}
    {{ encore_entry_link_tags('form') }}
    {{ encore_entry_script_tags('capteurs') }}
{% endblock %}